# Copyright (c) 2017 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.
#

################################################################################

includes:
#- ../app_locations.yml
- ../engine_locations.yml
#- ./tk-multi-loader2.yml
#- ./tk-multi-publish2.yml
#- ./tk-multi-screeningroom.yml
#- ./tk-multi-shotgunpanel.yml
#- ./tk-multi-snapshot.yml
- ./tk-multi-workfiles2.yml
################################################################################

# asset
settings.tk-katana.asset:
  apps:
    tk-multi-workfiles2: "@settings.tk-multi-workfiles2.launch_at_startup"
  menu_favourites:
  - {app_instance: tk-multi-workfiles2, name: File Open...}
  debug_logging: false
  location: "@engines.tk-katana.location"

# asset_step
settings.tk-katana.asset_step:
  apps:
    tk-multi-workfiles2: "@settings.tk-multi-workfiles2.katana.asset_step"
  menu_favourites:
  - {app_instance: tk-multi-workfiles2, name: File Open...}
  - {app_instance: tk-multi-workfiles2, name: File Save...}
  template_project: asset_work_area_katana
  location: "@engines.tk-katana.location"

# project
settings.tk-katana.project:
  apps:
    tk-multi-workfiles2: "@settings.tk-multi-workfiles2.launch_at_startup"
  location: "@engines.tk-katana.location"

# shot
settings.tk-katana.shot:
  apps:
    tk-multi-workfiles2: "@settings.tk-multi-workfiles2.launch_at_startup"
  menu_favourites:
  - {app_instance: tk-multi-workfiles2, name: File Open...}
  location: "@engines.tk-katana.location"

# shot_step
settings.tk-katana.shot_step:
  apps:
    tk-multi-about:
    tk-multi-workfiles2: "@settings.tk-multi-workfiles2.katana.shot_step"
  menu_favourites:
  - {app_instance: tk-multi-workfiles2, name: File Open...}
  - {app_instance: tk-multi-workfiles2, name: File Save...}
  template_project: shot_work_area_katana
  location: "@engines.tk-katana.location"
