    #
    # Katana
    #

    # define the location of a work area
    shot_work_area_katana:
        definition: '@shot_root/work/katana'
    # define the location of a publish area
    shot_publish_area_katana:
        definition: '@shot_root/publish/katana'
    # The location of WIP files
    katana_shot_work:
        definition: '@shot_root/work/katana/{Shot}_{Step}_v{version}.katana'
    # The location of backups of WIP files
    katana_shot_snapshot:
        definition: '@shot_root/work/katana/snapshots/{Shot}_{Step}_v{version}.{timestamp}.katana'
    # The location of published maya files
    katana_shot_publish:
        definition: '@shot_root/publish/katana/{Shot}_{Step}_v{version}.katana' 

    #
    # Katana
    #

    # define the location of a work area
    asset_work_area_katana:
        definition: '@asset_root/work/katana'
    # define the location of a publish area
    asset_publish_area_katana:
        definition: '@asset_root/publish/katana'
    # The location of WIP files
    katana_asset_work:
        definition: '@asset_root/work/katana/{name}.v{version}.katana'
    # The location of backups of WIP files
    katana_asset_snapshot:
        definition: '@asset_root/work/katana/snapshots/{name}.v{version}.{timestamp}.katana'
    # The location of published maya files
    katana_asset_publish:
        definition: '@asset_root/publish/katana/{name}.v{version}.katana'
