name: CI

# # Compile only on changes to src folder
# on:
#   push:
#     paths:
#     - 'src/**'
#   pull_request:
#     paths:
#     - 'src/**'
on: [push]

jobs:
  build:
    name: "Build Plugin for ${{ matrix.version }}"
    runs-on: ubuntu-latest
    container:
      image: centos:7
      volumes:
      - ${{ github.workspace }}/pybind11:${{ github.workspace }}/pybind11

    strategy:
      matrix:
        version: ["3.1v2"]  # ["3.1v2", "3.5v2"]

    steps:
    - uses: actions/checkout@v2

    - name: Checkout PyBind11
      uses: actions/checkout@v2
      with:
        repository: pybind/pybind11
        ref: v2.4.3
        path: pybind11/src

    - name: Install Dependencies
      run: |
        yum install -y centos-release-scl epel-release yum-utils
        curl -sSL https://raw.githubusercontent.com/wwfxuk/centos-vault-scl/master/activate.sh | bash
        yum install -y cmake3 devtoolset-6
        command -v cmake3

    - name: Check cmake3 still there
      run: command -v cmake3
