name: CI

# # Compile only on changes to src folder
# on:
#   push:
#     paths:
#     - 'src/**'
#   pull_request:
#     paths:
#     - 'src/**'
on: [push]

jobs:
  build:
    name: "Build Plugin for ${{ matrix.version }}"
    runs-on: ubuntu-latest
    container:
      image: centos:7
      volumes:
      - ${{ github.workspace }}/pybind11:${{ github.workspace }}/pybind11
      - ${{ github.workspace }}/katana:${{ github.workspace }}/katana
      - ${{ github.workspace }}/build:${{ github.workspace }}/build

    strategy:
      matrix:
        version: ["3.1v2"]  # ["3.1v2", "3.5v2"]

    steps:
    - uses: actions/checkout@v2

    - name: Checkout PyBind11
      uses: actions/checkout@v2
      with:
        repository: pybind/pybind11
        ref: v2.4.3
        path: pybind11/src

    - name: Install Dependencies, Katana ${{ matrix.version }}
      run: |
        mkdir katana build
        curl -sSL "http://thefoundry.s3.amazonaws.com/products/katana/releases/${{ matrix.version }}/Katana${{ matrix.version }}-linux-x86-release-64.tgz" \
        | tar -xzO katana_files.tar.gz | tar -xz -C katana &

        yum install -y centos-release-scl epel-release yum-utils
        curl -sSL https://raw.githubusercontent.com/wwfxuk/centos-vault-scl/master/activate.sh | bash
        yum install -y cmake3 devtoolset-6

        wait  # For Katana to finish extracting

    - name: Install PyBind11
      working-directory: pybind11/src
      run: |
        scl enable devtoolset-6 - << EOF
        cmake3 -DCMAKE_INSTALL_PREFIX="$(readlink -f ..)" -DPYBIND11_INSTALL=1 -DPYBIND11_TEST=0
        make -j "$(nproc)"
        make install
        EOF

    - name: Build plugin
      working-directory: build
      run: |
        cat /etc/centos-release
        command -v cmake3

        set -x -o pipefail
        PYBIND_INCLUDE_DIR="$(readlink -e ../pybind11/include)"
        KATANA_LOCATION="$(readlink -e ../katana)"
        KATANA_PYTHON="$(readlink -e ${KATANA_LOCATION}/bin/python2.7/include/python2.7)"
        PYTHON_LIB="$(readlink -e ${KATANA_LOCATION}/bin/python2.7/lib)"

        scl enable devtoolset-6 - << EOF
        gcc --version >> gcc-version
        EOF

    - name: Check built
      run: find build ! -type d
